formatVersion: 1
formatType: am-configuration
---
# basic AM functionality - the builtin apps are in 'apps'.
# installations will go into the standard /tmp/am hierarchy

applications:
  builtinAppsManifestDir: "${CONFIG_PWD}/apps"
  installedAppsManifestDir: "/tmp/neptune3-ui/manifests"
  appImageMountDir: "/tmp/neptune3-ui/image-mounts"
  database: "/tmp/neptune3-ui/apps.db"

# QML apps will be able to import from modules...

runtimes:
  qml:
    importPaths: [ "${CONFIG_PWD}/imports_shared" ]
    environmentVariables:
       QT_PLUGIN_PATH: ${CONFIG_PWD}
       SERVER_CONF_PATH: ${CONFIG_PWD}/server.conf
  native:
    importPaths: [ "${CONFIG_PWD}/imports_shared" ]
    environmentVariables:
      QT_PLUGIN_PATH: ${CONFIG_PWD}
      SERVER_CONF_PATH: ${CONFIG_PWD}/server.conf

# ... as well as the SystemUI

ui:
  fullscreen: no
  style: "${CONFIG_PWD}/styles/lucee"
  iconThemeName: "lucee"
  iconThemeSearchPaths: [ "${CONFIG_PWD}/imports_shared/assets/icons" ]
  mainQml: "${CONFIG_PWD}/Main.qml"
  importPaths: [ "${CONFIG_PWD}/imports_shared", "${CONFIG_PWD}/imports_system", "${CONFIG_PWD}/sysui" ]
  windowIcon: "${CONFIG_PWD}/imports_shared/assets/icons/lucee/sysui/ic-menu-home.png"

systemProperties:
    public:
      showCluster: yes
      showHUD: yes
      devMode: yes
    private:
      appStoreServerUrl: 'http://demoappsdeploy.qt.io:8512'
      orientation: 'Portrait'

# development setup: no security

flags:
  noSecurity: yes
  noUiWatchdog: yes

# default logging

logging:
  rules:
    - "*=false"
    - "qt.*=false"
    - "am.*=false"
    - "qml*=true"
    - "*.debug=false"
    - "*.warning=false"
    - "*.critical=true"

# simulate an internal and a SD-card installation location

installationLocations:
- id: "internal-0"
  installationPath: "/tmp/neptune3-ui/apps"
  documentPath: "/tmp/neptune3-ui/docs"
  mountPoint: "/tmp"
  isDefault: true
